import { ActionDefinition, ActionKey, PoseKeyframe } from './types';

const pose = (t: number, values: PoseKeyframe['pose'], rootX?: number): PoseKeyframe => ({
  t,
  rootX,
  pose: values,
});

const attackTrack = (
  windup: Partial<PoseKeyframe['pose']>,
  strike: Partial<PoseKeyframe['pose']>,
  recover: Partial<PoseKeyframe['pose']>,
  strikeRoot = 0,
): PoseKeyframe[] => [
  pose(0, {}),
  pose(0.22, windup),
  pose(0.5, strike, strikeRoot),
  pose(0.78, recover),
  pose(1, {}),
];

const defenseTrack = (
  hold: Partial<PoseKeyframe['pose']>,
  recover: Partial<PoseKeyframe['pose']> = {},
): PoseKeyframe[] => [
  pose(0, {}),
  pose(0.2, hold),
  pose(0.7, hold),
  pose(1, recover),
];

export const ACTIONS: Record<ActionKey, ActionDefinition> = {
  leftStraight: {
    key: 'leftStraight',
    label: '左直拳',
    group: 'attack',
    duration: 0.5,
    recovery: 0.15,
    staminaCost: 3,
    idealDistance: 156,
    tags: ['upper', 'straight', 'lead'],
    poseTrack: attackTrack(
      { torsoLean: 0.02, leadHandX: 16, rearHandY: -6, leadFootX: 8 },
      { torsoLean: 0.08, leadHandX: 132, leadHandY: -14, rearHandY: -4, leadFootX: 14 },
      { torsoLean: 0.03, leadHandX: 24, leadHandY: -4 },
      10,
    ),
    hitWindows: [
      { start: 0.22, end: 0.36, limb: 'leadHand', targets: ['head', 'torso'], damage: 8, balance: 10, push: 32, knockdown: 0.05 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.28, end: 0.62, followUps: ['rightStraight', 'leftHook', 'frontKick', 'punchKickCombo', 'bodyHookFlurry'] },
  },
  rightStraight: {
    key: 'rightStraight',
    label: '右直拳',
    group: 'attack',
    duration: 0.62,
    recovery: 0.18,
    staminaCost: 4,
    idealDistance: 160,
    tags: ['upper', 'straight', 'rear'],
    poseTrack: attackTrack(
      { torsoLean: -0.02, rearHandX: -18, rearHandY: 4, leadHandY: -8 },
      { torsoLean: 0.12, rearHandX: 144, rearHandY: -8, leadHandY: -4, leadFootX: 10, rearFootX: -10 },
      { torsoLean: 0.04, rearHandX: 12, rearHandY: -2 },
      14,
    ),
    hitWindows: [
      { start: 0.24, end: 0.4, limb: 'rearHand', targets: ['head', 'torso'], damage: 12, balance: 14, push: 44, knockdown: 0.09 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.36, end: 0.7, followUps: ['leftHook', 'rightHook', 'sideKick', 'comboPunches', 'overhandSmash'] },
  },
  leftHook: {
    key: 'leftHook',
    label: '左勾拳',
    group: 'attack',
    duration: 0.7,
    recovery: 0.22,
    staminaCost: 4,
    idealDistance: 142,
    tags: ['upper', 'hook', 'lead'],
    poseTrack: attackTrack(
      { torsoLean: -0.02, torsoShiftX: -6, leadHandX: -8, leadHandY: 12 },
      { torsoLean: 0.1, torsoShiftX: 14, leadHandX: 92, leadHandY: -34, leadFootX: 6 },
      { torsoLean: 0.02, torsoShiftX: 2, leadHandX: 18, leadHandY: -6 },
      8,
    ),
    hitWindows: [
      { start: 0.26, end: 0.46, limb: 'leadHand', targets: ['head', 'torso'], damage: 10, balance: 13, push: 38, knockdown: 0.08 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.4, end: 0.74, followUps: ['rightHook', 'frontKick', 'comboPunches', 'elbowSmash'] },
  },
  rightHook: {
    key: 'rightHook',
    label: '右勾拳',
    group: 'attack',
    duration: 0.78,
    recovery: 0.25,
    staminaCost: 5,
    idealDistance: 148,
    tags: ['upper', 'hook', 'rear'],
    poseTrack: attackTrack(
      { torsoShiftX: -10, torsoLean: -0.04, rearHandX: -26, rearHandY: 12 },
      { torsoShiftX: 18, torsoLean: 0.14, rearHandX: 104, rearHandY: -42, rearFootX: -12 },
      { torsoShiftX: 6, torsoLean: 0.04, rearHandX: 12, rearHandY: -10 },
      12,
    ),
    hitWindows: [
      { start: 0.3, end: 0.5, limb: 'rearHand', targets: ['head', 'torso'], damage: 14, balance: 17, push: 50, knockdown: 0.12 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.42, end: 0.8, followUps: ['frontKick', 'sideKick', 'comboPunches', 'overhandSmash'] },
  },
  swingPunch: {
    key: 'swingPunch',
    label: '摆拳',
    group: 'attack',
    duration: 0.9,
    recovery: 0.3,
    staminaCost: 6,
    idealDistance: 150,
    tags: ['upper', 'swing', 'power'],
    poseTrack: attackTrack(
      { torsoShiftX: -16, torsoLean: -0.08, rearHandX: -40, rearHandY: 18 },
      { torsoShiftX: 24, torsoLean: 0.2, rearHandX: 132, rearHandY: -34, leadHandY: -8 },
      { torsoShiftX: 8, torsoLean: 0.06, rearHandX: 20, rearHandY: -8 },
      16,
    ),
    hitWindows: [
      { start: 0.34, end: 0.58, limb: 'rearHand', targets: ['head', 'torso'], damage: 17, balance: 21, push: 58, knockdown: 0.18 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.5, end: 0.84, followUps: ['frontKick', 'ram', 'groundStomp'] },
  },
  overhandSmash: {
    key: 'overhandSmash',
    label: '下砸重拳',
    group: 'attack',
    duration: 0.92,
    recovery: 0.32,
    staminaCost: 7,
    idealDistance: 150,
    tags: ['upper', 'power', 'overhand'],
    poseTrack: attackTrack(
      { torsoShiftX: -18, torsoLean: -0.1, rearHandX: -36, rearHandY: -18, leadHandY: -10 },
      { torsoShiftX: 16, torsoLean: 0.22, rearHandX: 108, rearHandY: 42, leadFootX: 12 },
      { torsoShiftX: 6, torsoLean: 0.06, rearHandX: 16, rearHandY: -4 },
      18,
    ),
    hitWindows: [
      { start: 0.38, end: 0.58, limb: 'rearHand', targets: ['head', 'torso'], damage: 18, balance: 24, push: 56, knockdown: 0.26 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.54, end: 0.88, followUps: ['groundStomp', 'frontKick', 'ram'] },
  },
  elbowSmash: {
    key: 'elbowSmash',
    label: '近身肘击',
    group: 'attack',
    duration: 0.68,
    recovery: 0.2,
    staminaCost: 4,
    idealDistance: 118,
    tags: ['upper', 'close', 'elbow'],
    poseTrack: attackTrack(
      { torsoShiftX: 8, torsoLean: -0.08, rearHandY: -12, rearHandX: 8 },
      { torsoShiftX: 18, torsoLean: 0.1, rearHandX: 58, rearHandY: -30, leadHandY: -16 },
      { torsoShiftX: 4, torsoLean: 0.02, rearHandX: 6, rearHandY: -6 },
      8,
    ),
    hitWindows: [
      { start: 0.28, end: 0.46, limb: 'rearElbow', targets: ['head', 'torso'], damage: 12, balance: 16, push: 24, knockdown: 0.12 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.4, end: 0.74, followUps: ['kneeStrike', 'bodyHookFlurry', 'ram'] },
  },
  frontKick: {
    key: 'frontKick',
    label: '前踢',
    group: 'attack',
    duration: 0.88,
    recovery: 0.28,
    staminaCost: 6,
    idealDistance: 178,
    tags: ['lower', 'kick', 'front'],
    poseTrack: attackTrack(
      { torsoLean: -0.06, rearFootY: -52, rearFootX: 10, rearKneeLift: 28, rearHandY: -8 },
      { torsoLean: -0.12, rearFootX: 126, rearFootY: -148, rearKneeLift: 42, leadFootX: 10 },
      { torsoLean: -0.04, rearFootX: 20, rearFootY: -30, rearKneeLift: 12 },
      12,
    ),
    hitWindows: [
      { start: 0.34, end: 0.54, limb: 'rearFoot', targets: ['torso', 'head'], damage: 15, balance: 20, push: 60, knockdown: 0.15 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.48, end: 0.84, followUps: ['backStep', 'sideKick', 'axeKick'] },
  },
  sideKick: {
    key: 'sideKick',
    label: '侧踢',
    group: 'attack',
    duration: 1.02,
    recovery: 0.36,
    staminaCost: 8,
    idealDistance: 194,
    tags: ['lower', 'kick', 'power'],
    poseTrack: attackTrack(
      { torsoLean: -0.14, torsoShiftX: -10, rearFootY: -62, rearKneeLift: 34, rearHandY: -10, leadHandY: -8 },
      { torsoLean: -0.2, torsoShiftX: 10, rearFootX: 154, rearFootY: -132, rearKneeLift: 28, leadFootX: 4 },
      { torsoLean: -0.06, torsoShiftX: 0, rearFootX: 24, rearFootY: -24, rearKneeLift: 12 },
      18,
    ),
    hitWindows: [
      { start: 0.4, end: 0.6, limb: 'rearFoot', targets: ['torso', 'head'], damage: 20, balance: 25, push: 80, knockdown: 0.24 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.52, end: 0.88, followUps: ['backStep', 'quickRise', 'groundStomp'] },
  },
  axeKick: {
    key: 'axeKick',
    label: '下劈腿',
    group: 'attack',
    duration: 1.02,
    recovery: 0.34,
    staminaCost: 8,
    idealDistance: 176,
    tags: ['lower', 'kick', 'power'],
    poseTrack: attackTrack(
      { torsoLean: -0.18, rearFootY: -96, rearKneeLift: 54, rearHandY: -16 },
      { torsoLean: -0.08, rearFootX: 96, rearFootY: -182, rearKneeLift: 30, torsoShiftX: 10 },
      { torsoLean: -0.04, rearFootX: 18, rearFootY: -32, rearKneeLift: 12 },
      12,
    ),
    hitWindows: [
      { start: 0.42, end: 0.6, limb: 'rearFoot', targets: ['head', 'torso'], damage: 21, balance: 24, push: 46, knockdown: 0.28 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.56, end: 0.88, followUps: ['groundStomp', 'backStep'] },
  },
  spinningBackKick: {
    key: 'spinningBackKick',
    label: '转身后蹬',
    group: 'attack',
    duration: 1.08,
    recovery: 0.38,
    staminaCost: 9,
    idealDistance: 198,
    tags: ['lower', 'kick', 'power', 'charge'],
    poseTrack: [
      pose(0, {}),
      pose(0.22, { torsoShiftX: -18, torsoLean: -0.06, leadFootX: -10, rearFootX: -10 }),
      pose(0.46, { torsoShiftX: 14, torsoLean: 0.08, rearFootY: -56, rearKneeLift: 34 }, 12),
      pose(0.72, { torsoShiftX: 26, torsoLean: 0.12, rearFootX: 162, rearFootY: -112, rearKneeLift: 22 }, 26),
      pose(1, { torsoShiftX: 4, torsoLean: 0.02 }),
    ],
    hitWindows: [
      { start: 0.62, end: 0.82, limb: 'rearFoot', targets: ['torso', 'head'], damage: 22, balance: 27, push: 86, knockdown: 0.32 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.74, end: 0.96, followUps: ['groundStomp', 'backHop'] },
  },
  lowSweep: {
    key: 'lowSweep',
    label: '低扫腿',
    group: 'attack',
    duration: 0.96,
    recovery: 0.34,
    staminaCost: 6,
    idealDistance: 152,
    tags: ['lower', 'sweep', 'low'],
    poseTrack: attackTrack(
      { torsoLean: -0.1, pelvisY: 6, rearFootY: -12, rearHandY: -6 },
      { torsoLean: -0.16, pelvisY: 8, rearFootX: 114, rearFootY: -10, rearKneeLift: -10 },
      { torsoLean: -0.04, pelvisY: 2, rearFootX: 18, rearFootY: -4 },
      10,
    ),
    hitWindows: [
      { start: 0.3, end: 0.54, limb: 'rearFoot', targets: ['low'], damage: 10, balance: 28, push: 30, knockdown: 0.22 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.46, end: 0.82, followUps: ['rightStraight', 'ram', 'groundStomp'] },
  },
  kneeStrike: {
    key: 'kneeStrike',
    label: '膝撞',
    group: 'attack',
    duration: 0.74,
    recovery: 0.22,
    staminaCost: 5,
    idealDistance: 114,
    tags: ['lower', 'close', 'knee'],
    poseTrack: attackTrack(
      { torsoLean: -0.08, torsoShiftX: 6, rearFootY: -56, rearKneeLift: 38 },
      { torsoLean: -0.1, torsoShiftX: 18, rearFootX: 58, rearFootY: -132, rearKneeLift: 56 },
      { torsoLean: -0.03, torsoShiftX: 6, rearFootX: 10, rearFootY: -24, rearKneeLift: 16 },
      12,
    ),
    hitWindows: [
      { start: 0.26, end: 0.46, limb: 'rearKnee', targets: ['torso', 'head'], damage: 16, balance: 21, push: 32, knockdown: 0.14 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.38, end: 0.7, followUps: ['leftHook', 'rightHook', 'groundCounter', 'elbowSmash'] },
  },
  ram: {
    key: 'ram',
    label: '冲撞',
    group: 'attack',
    duration: 0.7,
    recovery: 0.22,
    staminaCost: 5,
    idealDistance: 124,
    tags: ['body', 'charge', 'power'],
    poseTrack: attackTrack(
      { torsoLean: 0.04, torsoShiftX: 4, leadFootX: 12, rearFootX: -8 },
      { torsoLean: 0.18, torsoShiftX: 26, leadFootX: 22, rearFootX: 2 },
      { torsoLean: 0.05, torsoShiftX: 6 },
      22,
    ),
    hitWindows: [
      { start: 0.22, end: 0.44, limb: 'torso', targets: ['torso'], damage: 13, balance: 26, push: 90, knockdown: 0.22 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.34, end: 0.64, followUps: ['kneeStrike', 'leftHook', 'groundStomp'] },
  },
  comboPunches: {
    key: 'comboPunches',
    label: '组合连拳',
    group: 'combo',
    duration: 1.08,
    recovery: 0.3,
    staminaCost: 8,
    idealDistance: 152,
    tags: ['combo', 'upper'],
    poseTrack: [
      pose(0, {}),
      pose(0.18, { leadHandX: 18, torsoLean: 0.02 }),
      pose(0.3, { leadHandX: 116, leadHandY: -8, torsoLean: 0.08 }, 10),
      pose(0.48, { rearHandX: -24, torsoLean: -0.02 }),
      pose(0.66, { rearHandX: 128, rearHandY: -18, torsoLean: 0.14 }, 14),
      pose(0.82, { leadHandX: -8, leadHandY: 14, torsoShiftX: -8 }),
      pose(1, { leadHandX: 82, leadHandY: -28, torsoLean: 0.1 }, 8),
    ],
    hitWindows: [
      { start: 0.22, end: 0.34, limb: 'leadHand', targets: ['head', 'torso'], damage: 6, balance: 8, push: 22, knockdown: 0.04 },
      { start: 0.54, end: 0.72, limb: 'rearHand', targets: ['head', 'torso'], damage: 9, balance: 11, push: 26, knockdown: 0.06 },
      { start: 0.86, end: 1, limb: 'leadHand', targets: ['head', 'torso'], damage: 10, balance: 13, push: 30, knockdown: 0.08 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.82, end: 1, followUps: ['frontKick', 'sideKick', 'slipBlockCounter', 'overhandSmash'] },
  },
  bodyHookFlurry: {
    key: 'bodyHookFlurry',
    label: '贴身连肋击',
    group: 'combo',
    duration: 1.06,
    recovery: 0.28,
    staminaCost: 8,
    idealDistance: 124,
    tags: ['combo', 'close', 'body'],
    poseTrack: [
      pose(0, {}),
      pose(0.18, { torsoShiftX: 10, torsoLean: -0.04, leadHandY: 10 }),
      pose(0.34, { leadHandX: 86, leadHandY: 16, torsoShiftX: 14 }, 6),
      pose(0.54, { rearHandX: 72, rearHandY: 12, torsoShiftX: 18 }, 8),
      pose(0.76, { leadHandX: 92, leadHandY: -2, torsoShiftX: 12 }, 6),
      pose(1, { torsoShiftX: 2, torsoLean: 0.02 }),
    ],
    hitWindows: [
      { start: 0.26, end: 0.38, limb: 'leadHand', targets: ['torso'], damage: 8, balance: 10, push: 16, knockdown: 0.04, staminaDamage: 5 },
      { start: 0.46, end: 0.6, limb: 'rearHand', targets: ['torso'], damage: 9, balance: 11, push: 18, knockdown: 0.05, staminaDamage: 6 },
      { start: 0.68, end: 0.82, limb: 'leadHand', targets: ['head', 'torso'], damage: 10, balance: 13, push: 24, knockdown: 0.08 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.74, end: 1, followUps: ['overhandSmash', 'kneeStrike', 'groundStomp'] },
  },
  punchKickCombo: {
    key: 'punchKickCombo',
    label: '拳腿组合',
    group: 'combo',
    duration: 1.2,
    recovery: 0.34,
    staminaCost: 9,
    idealDistance: 174,
    tags: ['combo', 'mixed'],
    poseTrack: [
      pose(0, {}),
      pose(0.2, { leadHandX: 22, torsoLean: 0.02 }),
      pose(0.32, { leadHandX: 118, leadHandY: -8, torsoLean: 0.08 }, 8),
      pose(0.56, { rearFootY: -58, rearKneeLift: 34, torsoLean: -0.08 }),
      pose(0.82, { rearFootX: 142, rearFootY: -142, rearKneeLift: 42, torsoLean: -0.16 }, 14),
      pose(1, { rearFootX: 20, rearFootY: -18, torsoLean: -0.04 }),
    ],
    hitWindows: [
      { start: 0.22, end: 0.36, limb: 'leadHand', targets: ['head', 'torso'], damage: 7, balance: 8, push: 22, knockdown: 0.04 },
      { start: 0.68, end: 0.9, limb: 'rearFoot', targets: ['torso', 'head'], damage: 16, balance: 19, push: 56, knockdown: 0.14 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.82, end: 1, followUps: ['backStep', 'shuffleStep', 'axeKick'] },
  },
  fiveKickCombo: {
    key: 'fiveKickCombo',
    label: '五连踢',
    group: 'combo',
    duration: 1.8,
    recovery: 0.44,
    staminaCost: 14,
    idealDistance: 180,
    tags: ['combo', 'lower'],
    poseTrack: [
      pose(0, {}),
      pose(0.16, { rearFootY: -42, rearKneeLift: 24, torsoLean: -0.04 }),
      pose(0.28, { rearFootX: 82, rearFootY: -96, rearKneeLift: 34 }, 8),
      pose(0.42, { leadFootY: -36, leadKneeLift: 22, torsoLean: -0.05 }),
      pose(0.54, { leadFootX: 72, leadFootY: -82, leadKneeLift: 30 }, 8),
      pose(0.68, { rearFootY: -46, rearKneeLift: 24 }),
      pose(0.78, { rearFootX: 90, rearFootY: -92, rearKneeLift: 28 }, 8),
      pose(0.88, { leadFootY: -44, leadKneeLift: 28 }),
      pose(0.96, { leadFootX: 104, leadFootY: -96, leadKneeLift: 34 }, 10),
      pose(1, { rearFootX: 148, rearFootY: -138, rearKneeLift: 42, torsoLean: -0.16 }, 16),
    ],
    hitWindows: [
      { start: 0.18, end: 0.3, limb: 'rearFoot', targets: ['low', 'torso'], damage: 5, balance: 7, push: 16, knockdown: 0.02 },
      { start: 0.44, end: 0.56, limb: 'leadFoot', targets: ['low', 'torso'], damage: 5, balance: 7, push: 16, knockdown: 0.02 },
      { start: 0.68, end: 0.8, limb: 'rearFoot', targets: ['low', 'torso'], damage: 6, balance: 8, push: 18, knockdown: 0.03 },
      { start: 0.86, end: 0.98, limb: 'leadFoot', targets: ['torso', 'head'], damage: 7, balance: 9, push: 20, knockdown: 0.04 },
      { start: 0.94, end: 1, limb: 'rearFoot', targets: ['torso', 'head'], damage: 13, balance: 17, push: 36, knockdown: 0.14 },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.94, end: 1, followUps: ['backHop', 'resetStance', 'spinningBackKick'] },
  },
  groundStomp: {
    key: 'groundStomp',
    label: '倒地踩踏',
    group: 'attack',
    duration: 0.82,
    recovery: 0.24,
    staminaCost: 5,
    idealDistance: 112,
    tags: ['ground', 'stomp', 'pressure'],
    poseTrack: [
      pose(0, {}),
      pose(0.26, { torsoLean: -0.08, rearFootY: -52, rearKneeLift: 30, leadHandY: -10 }),
      pose(0.56, { torsoLean: 0.02, rearFootX: 92, rearFootY: -8, rearKneeLift: -2 }, 10),
      pose(1, {}),
    ],
    hitWindows: [
      { start: 0.32, end: 0.72, limb: 'rearFoot', targets: ['torso', 'low'], damage: 5, balance: 7, push: 10, knockdown: 0.06, allowGround: true, ignoreDefense: true },
    ],
    defenseWindows: [],
    chainWindow: { start: 0.62, end: 0.92, followUps: ['backStep', 'headShell', 'overhandSmash'] },
  },
  groundCounter: {
    key: 'groundCounter',
    label: '倒地反击',
    group: 'recovery',
    duration: 0.96,
    recovery: 0.26,
    staminaCost: 5,
    idealDistance: 118,
    tags: ['ground', 'counter'],
    poseTrack: [
      pose(0, { pelvisY: 16, torsoLean: -0.2, rearFootY: -8 }),
      pose(0.28, { pelvisY: 8, torsoLean: -0.08, rearFootY: -22, rearKneeLift: 18 }),
      pose(0.52, { pelvisY: 0, torsoLean: 0.04, rearHandX: 118, rearHandY: -8 }, 10),
      pose(1, {}),
    ],
    hitWindows: [
      { start: 0.46, end: 0.64, limb: 'rearHand', targets: ['torso', 'head'], damage: 14, balance: 15, push: 34, knockdown: 0.12, allowGround: true },
    ],
    defenseWindows: [
      { start: 0.08, end: 0.28, coverage: ['mid', 'low'], mode: 'brace', mitigation: 0.4, interrupt: 0.15 },
    ],
    chainWindow: { start: 0.58, end: 0.94, followUps: ['quickRise'] },
    downUsable: true,
  },
  crossBlock: {
    key: 'crossBlock',
    label: '十字格挡',
    group: 'defense',
    duration: 0.7,
    recovery: 0.14,
    staminaCost: 2,
    idealDistance: 166,
    tags: ['defense', 'high'],
    poseTrack: defenseTrack({ leadHandY: -42, rearHandY: -42, leadHandX: 20, rearHandX: 6, torsoLean: -0.06 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.14, end: 0.72, coverage: ['high', 'mid'], mode: 'block', mitigation: 0.45, interrupt: 0 },
    ],
    chainWindow: { start: 0.36, end: 0.82, followUps: ['slipBlockCounter', 'singleParry', 'backStep'] },
  },
  singleParry: {
    key: 'singleParry',
    label: '单手拍挡',
    group: 'defense',
    duration: 0.54,
    recovery: 0.14,
    staminaCost: 2,
    idealDistance: 158,
    tags: ['defense', 'parry'],
    poseTrack: defenseTrack({ leadHandX: 44, leadHandY: -22, rearHandY: -12, torsoShiftX: 4 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.18, end: 0.42, coverage: ['high', 'mid'], mode: 'parry', mitigation: 0.2, interrupt: 0.28 },
    ],
    chainWindow: { start: 0.28, end: 0.66, followUps: ['rightStraight', 'leftHook', 'slipBlockCounter', 'elbowSmash'] },
  },
  elbowShield: {
    key: 'elbowShield',
    label: '肘挡',
    group: 'defense',
    duration: 0.66,
    recovery: 0.16,
    staminaCost: 3,
    idealDistance: 144,
    tags: ['defense', 'close'],
    poseTrack: defenseTrack({ leadHandY: -36, rearHandY: -28, leadHandX: 12, rearHandX: -12, torsoLean: -0.08 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.16, end: 0.68, coverage: ['high', 'mid'], mode: 'block', mitigation: 0.35, interrupt: 0.1 },
    ],
    chainWindow: { start: 0.38, end: 0.84, followUps: ['kneeStrike', 'leftHook', 'bodyHookFlurry'] },
  },
  downPressBlock: {
    key: 'downPressBlock',
    label: '下压格挡',
    group: 'defense',
    duration: 0.68,
    recovery: 0.16,
    staminaCost: 2,
    idealDistance: 148,
    tags: ['defense', 'low'],
    poseTrack: defenseTrack({ pelvisY: 4, leadHandY: 8, rearHandY: 10, torsoLean: -0.1 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.14, end: 0.72, coverage: ['low', 'mid'], mode: 'block', mitigation: 0.42, interrupt: 0.05 },
    ],
    chainWindow: { start: 0.34, end: 0.84, followUps: ['lowSweep', 'duckSlipKick'] },
  },
  headShell: {
    key: 'headShell',
    label: '抱架护头',
    group: 'defense',
    duration: 0.84,
    recovery: 0.18,
    staminaCost: 3,
    idealDistance: 166,
    tags: ['defense', 'shell'],
    poseTrack: defenseTrack({ pelvisY: 6, torsoLean: -0.14, leadHandY: -46, rearHandY: -44, leadHandX: 12, rearHandX: -6 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.12, end: 0.9, coverage: ['high', 'mid'], mode: 'brace', mitigation: 0.52, interrupt: 0.04 },
    ],
    chainWindow: { start: 0.42, end: 0.92, followUps: ['quickRise', 'backStep'] },
  },
  sinkGuard: {
    key: 'sinkGuard',
    label: '沉身防守',
    group: 'defense',
    duration: 0.8,
    recovery: 0.16,
    staminaCost: 3,
    idealDistance: 146,
    tags: ['defense', 'sink'],
    poseTrack: defenseTrack({ pelvisY: 12, torsoLean: -0.08, leadHandY: -24, rearHandY: -18, leadFootX: -2, rearFootX: -8 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.14, end: 0.86, coverage: ['mid', 'low'], mode: 'brace', mitigation: 0.46, interrupt: 0.08 },
    ],
    chainWindow: { start: 0.44, end: 0.92, followUps: ['kneeStrike', 'frontKick', 'duckEvade'] },
  },
  sideGuard: {
    key: 'sideGuard',
    label: '侧身防守',
    group: 'defense',
    duration: 0.76,
    recovery: 0.18,
    staminaCost: 3,
    idealDistance: 154,
    tags: ['defense', 'angle'],
    poseTrack: defenseTrack({ torsoShiftX: -18, torsoLean: -0.04, leadHandY: -26, rearHandY: -18, leadFootX: -10, rearFootX: -6 }),
    hitWindows: [],
    defenseWindows: [
      { start: 0.16, end: 0.84, coverage: ['high', 'mid'], mode: 'block', mitigation: 0.4, interrupt: 0.08 },
    ],
    chainWindow: { start: 0.36, end: 0.9, followUps: ['swingPunch', 'sideKick', 'shuffleStep', 'spinningBackKick'] },
  },
  slipLeft: {
    key: 'slipLeft',
    label: '左侧闪',
    group: 'movement',
    duration: 0.46,
    recovery: 0.1,
    staminaCost: 2,
    idealDistance: 166,
    tags: ['evade', 'angle'],
    poseTrack: [
      pose(0, {}),
      pose(0.3, { torsoShiftX: -18, headShiftX: -12, torsoLean: -0.08, leadFootX: -6, rearFootX: -10 }, -18),
      pose(1, { torsoShiftX: 0, headShiftX: 0, torsoLean: 0 }),
    ],
    hitWindows: [],
    defenseWindows: [
      { start: 0.12, end: 0.42, coverage: ['high', 'mid'], mode: 'parry', mitigation: 0.2, interrupt: 0.05 },
    ],
    chainWindow: { start: 0.24, end: 0.62, followUps: ['rightStraight', 'slipBlockCounter', 'ram'] },
  },
  slipRight: {
    key: 'slipRight',
    label: '右侧闪',
    group: 'movement',
    duration: 0.46,
    recovery: 0.1,
    staminaCost: 2,
    idealDistance: 166,
    tags: ['evade', 'angle'],
    poseTrack: [
      pose(0, {}),
      pose(0.3, { torsoShiftX: 18, headShiftX: 12, torsoLean: 0.08, leadFootX: 6, rearFootX: 8 }, 18),
      pose(1, { torsoShiftX: 0, headShiftX: 0, torsoLean: 0 }),
    ],
    hitWindows: [],
    defenseWindows: [
      { start: 0.12, end: 0.42, coverage: ['high', 'mid'], mode: 'parry', mitigation: 0.2, interrupt: 0.05 },
    ],
    chainWindow: { start: 0.24, end: 0.62, followUps: ['leftHook', 'slipBlockCounter', 'punchKickCombo'] },
  },
  duckEvade: {
    key: 'duckEvade',
    label: '下潜闪避',
    group: 'movement',
    duration: 0.58,
    recovery: 0.12,
    staminaCost: 3,
    idealDistance: 146,
    tags: ['evade', 'duck'],
    poseTrack: [
      pose(0, {}),
      pose(0.28, { pelvisY: 14, torsoLean: -0.12, headLift: 8, leadHandY: -16, rearHandY: -14 }, 6),
      pose(0.62, { pelvisY: 18, torsoLean: -0.08, headLift: 10 }, 8),
      pose(1, {}),
    ],
    hitWindows: [],
    defenseWindows: [
      { start: 0.16, end: 0.56, coverage: ['high'], mode: 'brace', mitigation: 0.15, interrupt: 0.08 },
    ],
    chainWindow: { start: 0.36, end: 0.82, followUps: ['kneeStrike', 'duckSlipKick', 'lowSweep'] },
  },
  backStep: {
    key: 'backStep',
    label: '后撤步',
    group: 'movement',
    duration: 0.52,
    recovery: 0.12,
    staminaCost: 2,
    idealDistance: 212,
    tags: ['evade', 'retreat'],
    poseTrack: [
      pose(0, {}),
      pose(0.3, { torsoLean: 0.04, leadFootX: -24, rearFootX: -36, leadKneeLift: 8, rearKneeLift: 10 }, -34),
      pose(1, {}),
    ],
    hitWindows: [],
    defenseWindows: [],
    chainWindow: { start: 0.22, end: 0.7, followUps: ['frontKick', 'sideKick', 'resetStance', 'spinningBackKick'] },
  },
  backHop: {
    key: 'backHop',
    label: '后跳',
    group: 'movement',
    duration: 0.62,
    recovery: 0.16,
    staminaCost: 4,
    idealDistance: 236,
    tags: ['evade', 'hop'],
    poseTrack: [
      pose(0, {}),
      pose(0.26, { pelvisY: -8, leadFootX: -16, rearFootX: -24, leadKneeLift: 18, rearKneeLift: 18 }, -18),
      pose(0.52, { pelvisY: -14, leadFootX: -28, rearFootX: -42, leadKneeLift: 24, rearKneeLift: 24 }, -60),
      pose(1, {}),
    ],
    hitWindows: [],
    defenseWindows: [],
    chainWindow: { start: 0.46, end: 0.84, followUps: ['frontKick', 'sideKick', 'axeKick'] },
  },
  shuffleStep: {
    key: 'shuffleStep',
    label: '滑步移位',
    group: 'movement',
    duration: 0.58,
    recovery: 0.1,
    staminaCost: 2,
    idealDistance: 160,
    tags: ['movement', 'angle'],
    poseTrack: [
      pose(0, {}),
      pose(0.28, { torsoShiftX: -12, leadFootX: -22, rearFootX: -14, leadKneeLift: 10, rearKneeLift: 8 }, -28),
      pose(0.58, { torsoShiftX: 8, leadFootX: 14, rearFootX: 8, leadKneeLift: 8, rearKneeLift: 8 }, 12),
      pose(1, {}),
    ],
    hitWindows: [],
    defenseWindows: [],
    chainWindow: { start: 0.36, end: 0.82, followUps: ['leftStraight', 'rightHook', 'ram', 'bodyHookFlurry'] },
  },
  braceFall: {
    key: 'braceFall',
    label: '受控倒地',
    group: 'recovery',
    duration: 0.72,
    recovery: 0.14,
    staminaCost: 1,
    idealDistance: 120,
    tags: ['ground', 'brace'],
    poseTrack: [
      pose(0, { pelvisY: 10, torsoLean: -0.08 }),
      pose(0.48, { pelvisY: 18, torsoLean: -0.18, leadHandY: -12, rearHandY: -8 }),
      pose(1, { pelvisY: 18, torsoLean: -0.22 }),
    ],
    hitWindows: [],
    defenseWindows: [
      { start: 0.14, end: 0.72, coverage: ['mid', 'low'], mode: 'brace', mitigation: 0.38, interrupt: 0 },
    ],
    downUsable: true,
  },
  quickRise: {
    key: 'quickRise',
    label: '快速起身',
    group: 'recovery',
    duration: 0.82,
    recovery: 0.16,
    staminaCost: 4,
    idealDistance: 132,
    tags: ['ground', 'rise'],
    poseTrack: [
      pose(0, { pelvisY: 18, torsoLean: -0.18 }),
      pose(0.42, { pelvisY: 8, torsoLean: -0.06, leadFootX: -6, rearFootX: -12 }),
      pose(0.74, { pelvisY: 2, torsoLean: 0.02 }, 8),
      pose(1, {}),
    ],
    hitWindows: [],
    defenseWindows: [
      { start: 0.16, end: 0.56, coverage: ['mid', 'low'], mode: 'brace', mitigation: 0.3, interrupt: 0.02 },
    ],
    chainWindow: { start: 0.68, end: 1, followUps: ['groundCounter', 'crossBlock', 'backStep'] },
    downUsable: true,
  },
  resetStance: {
    key: 'resetStance',
    label: '重心回正',
    group: 'recovery',
    duration: 0.52,
    recovery: 0.08,
    staminaCost: 1,
    idealDistance: 160,
    tags: ['recover'],
    poseTrack: defenseTrack({ torsoLean: 0, pelvisY: 0, leadHandY: -4, rearHandY: -4 }, {}),
    hitWindows: [],
    defenseWindows: [
      { start: 0.12, end: 0.48, coverage: ['mid'], mode: 'brace', mitigation: 0.15, interrupt: 0 },
    ],
  },
  slipBlockCounter: {
    key: 'slipBlockCounter',
    label: '闪挡反击',
    group: 'combo',
    duration: 0.96,
    recovery: 0.24,
    staminaCost: 7,
    idealDistance: 156,
    tags: ['combo', 'counter'],
    poseTrack: [
      pose(0, {}),
      pose(0.2, { torsoShiftX: -18, headShiftX: -12, torsoLean: -0.08 }, -16),
      pose(0.4, { leadHandY: -42, rearHandY: -38, torsoLean: -0.1 }),
      pose(0.72, { rearHandX: 124, rearHandY: -14, torsoLean: 0.14 }, 12),
      pose(1, {}),
    ],
    hitWindows: [
      { start: 0.62, end: 0.8, limb: 'rearHand', targets: ['head', 'torso'], damage: 13, balance: 16, push: 34, knockdown: 0.11 },
    ],
    defenseWindows: [
      { start: 0.18, end: 0.5, coverage: ['high', 'mid'], mode: 'block', mitigation: 0.34, interrupt: 0.08 },
    ],
    chainWindow: { start: 0.72, end: 0.98, followUps: ['frontKick', 'sideKick', 'overhandSmash'] },
  },
  duckSlipKick: {
    key: 'duckSlipKick',
    label: '潜闪踢',
    group: 'combo',
    duration: 1.08,
    recovery: 0.28,
    staminaCost: 8,
    idealDistance: 174,
    tags: ['combo', 'evade'],
    poseTrack: [
      pose(0, {}),
      pose(0.24, { pelvisY: 14, torsoLean: -0.12, headLift: 8 }, 6),
      pose(0.44, { torsoShiftX: -16, headShiftX: -10 }, -18),
      pose(0.72, { rearFootX: 134, rearFootY: -136, rearKneeLift: 38, torsoLean: -0.14 }, 12),
      pose(1, {}),
    ],
    hitWindows: [
      { start: 0.68, end: 0.86, limb: 'rearFoot', targets: ['torso', 'head'], damage: 16, balance: 19, push: 58, knockdown: 0.16 },
    ],
    defenseWindows: [
      { start: 0.16, end: 0.48, coverage: ['high'], mode: 'brace', mitigation: 0.2, interrupt: 0.04 },
    ],
    chainWindow: { start: 0.78, end: 1, followUps: ['backStep', 'sideKick', 'groundStomp'] },
  },
  blockCircleCounter: {
    key: 'blockCircleCounter',
    label: '绕挡反击',
    group: 'combo',
    duration: 1.12,
    recovery: 0.28,
    staminaCost: 8,
    idealDistance: 150,
    tags: ['combo', 'angle'],
    poseTrack: [
      pose(0, {}),
      pose(0.2, { leadHandY: -40, rearHandY: -40, torsoLean: -0.06 }),
      pose(0.46, { torsoShiftX: -20, leadFootX: -20, rearFootX: -8 }, -22),
      pose(0.76, { torsoShiftX: 18, rearHandX: 114, rearHandY: -28, torsoLean: 0.12 }, 12),
      pose(1, {}),
    ],
    hitWindows: [
      { start: 0.7, end: 0.88, limb: 'rearHand', targets: ['head', 'torso'], damage: 14, balance: 17, push: 36, knockdown: 0.12 },
    ],
    defenseWindows: [
      { start: 0.16, end: 0.38, coverage: ['high', 'mid'], mode: 'block', mitigation: 0.36, interrupt: 0.04 },
    ],
    chainWindow: { start: 0.78, end: 1, followUps: ['leftHook', 'ram', 'spinningBackKick'] },
  },
};
